# Pipeline for Nebula Logger
name: Build

env:
  SF_DISABLE_AUTOUPDATE: true
  SF_LOG_LEVEL: debug
  SF_SKIP_NEW_VERSION_CHECK: true

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - config/scratch-orgs/**
      - nebula-logger/**
      - sfdx-project.json
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/**
      - config/scratch-orgs/**
      - nebula-logger/**
      - sfdx-project.json

jobs:
  code-quality-tests:
    
    name: 'Run Code Quality Tests'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - name: Scan with Endor Labs
        uses: endorlabs/github-action@main # This workflow uses the Endor Labs GitHub action to scan.
        with:
          namespace: 'gard-test'
          scan_summary_output_type: 'json'
          pr: false
          scan_secrets: true
          scan_dependencies: true
